### ISSUE TITLE
how to add $SERVICEEXECUTIONTIME$ to output of check_http_json

### ISSUE THREAD

**Issue by licett** [drewkerrigan/nagios-http-json#16]
hi, I want to import $SERVICEEXECUTIONTIME$ param to pnp, so I can get a graphic overview of my api cost.

And I check the format that pnp can parse,  I must add $SERVICEEXECUTIONTIME$ to output of check_http_json.

Is it right? If so , how can I manage it ?

**Comment by drewkerrigan** [comment]
@licett I think you're talking about the macro defined in: https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/macrolist.html ?

```
$SERVICEEXECUTIONTIME$	A (floating point) number indicating the number of seconds that the service check took to execute (i.e. the amount of time the check was executing).
```

That is a macro that should be provided by Nagios... I'm not familiar with PNP, and am unsure how you would get it to consume that particular macro. The instructions at https://nagios-plugins.org/doc/guidelines.html don't provide any ability for plugins to display that type of data themselves.
