### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by boldandbusted** [drewkerrigan/nagios-http-json#21]
$ ./check_http_json.py -H 184.172.237.226:51234 -m "node_gets"
Traceback (most recent call last):
  File "./check_http_json.py", line 421, in <module>
    nagios.append_unknown("HTTPError[%s], url:%s" % (str(e.code), url))
  File "./check_http_json.py", line 59, in append_unknown
    self.critical_message += critical_message
NameError: global name 'critical_message' is not defined

I'll be glad to give you more information about my environment, if needed. Thanks!

**Comment by drewkerrigan** [comment]
Whoops, good catch.
