### ISSUE TITLE
Adding a parameter to allow perf output on the status line

### ISSUE THREAD

**Issue by oragain** [drewkerrigan/nagios-http-json#27]
Hi Drew,

Would you be open to add a parameter so that the perf output also shows on the status information line? That way you don't need to go to the graph to see the value.

I always liked to be able to grasp the values directly from the status information without having to go down to the graph.

Thanks
Olivier

**Comment by marxin** [comment]
Is it fixed with the current master:

```
$ ./check_http_json.py -H jsonplaceholder.typicode.com -p todos -w '(10).id,5'
WARNING: Status WARNING. Value (11) for key (10).id was outside the range 0:5.
```

**Comment by martialblog** [comment]
Should be fixed in current master. Please reopen if still persists
