### ISSUE TITLE
License for this plugin?

### ISSUE THREAD

**Issue by saintaardvark** [drewkerrigan/nagios-http-json#3]
Hi there -- I just came across this plugin, and I'd like to use it -- but can you let me know what license it's released under?  (I'm happy to throw out GPLv3 as a suggestion, but that's just me.)

Thanks very much for your time!

**Comment by drewkerrigan** [comment]
@saurabh-hirani I completely forgot that I even created this plugin! I generally use Apache 2.0 if that is agreeable; I'll throw that in there now.

**Comment by saurabh-hirani** [comment]
Cool. Thanks.
