### ISSUE TITLE
Key may not contain ,

### ISSUE THREAD

**Issue by JonasJurczok** [drewkerrigan/nagios-http-json#35]
Hi,
we are trying to use your plugin to monitor our ActiveMQ. Unfortunately the batch checking does not work and we now have to create one check / queue.

During the experiments we found that if one of the keys in your json contains a , the python script will fail in line 202 on the split().
E.g. ActiveMQ returns a status key of this form: "org.apache.activemq:brokerName=static-broker-1-master,destinationName=your-queue-name,destinationType=Queue,type=Broker"

As you can see this contians multiple , that you actually cannot get rid of.

There exists a workaround. If you specify the exact queue name and attribute you are looking for in the url the result will just contain a "value" key. This means no bulk checking, though...

What do you think? Is this worth a fix?

**Comment by martialblog** [comment]
Hi, I just tested this and the issue here is the separator, which is `.` by default

CLI option: `[-f SEPARATOR]`

See also:
https://github.com/drewkerrigan/nagios-http-json/commit/781de1d628e1ac72e0845de0d3f65c4b4c432d04
