### ISSUE TITLE
Http 403

### ISSUE THREAD

**Issue by gianks** [drewkerrigan/nagios-http-json#42]
Hi, i'm trying to use the plugin but i get a 403 using both http and https: **UNKNOWN: Status UNKNOWN.HTTPError[403]**.
The full url given back in the output works fine when used with wget or any browser from the same machine.

Tried adding ** -A '{"content-type": "application/json"}'** but same result.
Any ideas?

**Comment by martialblog** [comment]
Hi, should be solved with https://github.com/drewkerrigan/nagios-http-json/commit/7858382bbed7b83f77457faa36b4f5e3f0331b54
