### ISSUE TITLE
Add New Maintainer

### ISSUE THREAD

**Issue by martialblog** [drewkerrigan/nagios-http-json#44]
Hey,

first of: great project. We're using it and it's great :+1: 
However, given there there are no more updates recently, I'd suggest adding a new maintainer. So that there aren't endless forks and we can ensure new features.

Of course, I'd volunteer myself if you don't mind. 

Cheers,
Markus

**Comment by drewkerrigan** [comment]
Hello Markus! My apologies for letting this project completely slip my mind. I've added you as a maintainer, feel free to suggest others as well!

**Comment by martialblog** [comment]
@drewkerrigan Hey, no worries! Thanks. I'll take good care of it.
