### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by martialblog** [drewkerrigan/nagios-http-json#48]
This module needs to move to Python 3 in the near future, since Python 2.7 is no longer supported

https://www.python.org/dev/peps/pep-0373/

**Comment by marxin** [comment]
I would like to see the script in openSUSE. And yes, Python2 packages are deprecated, so I would like to see the script converted to Python3 soonish.

**Comment by marxin** [comment]
I would probably close this.

**Comment by martialblog** [comment]
@marxin Hi, I was acually planing on doing some more tests tomorrow and then create a 2.* release with Python 3

**Comment by marxin** [comment]
Great, thanks.

**Comment by martialblog** [comment]
Python3 Branch works. See https://github.com/drewkerrigan/nagios-http-json/tree/python3

Gonna check if there's some other stuff I want to put into 2.* - if not, the release will come soon,
