### ISSUE TITLE
Bug if array element is 0

### ISSUE THREAD

**Issue by vanso-hubsi** [drewkerrigan/nagios-http-json#64]
Hi!
First of all, thank you for that plugin!

I just wanted to start using it, when I stumbled across a possible bug: 
I wanted to collect metrics of an integer value in an array and then found that if that value equals "0" the whole json is returned as metrics value.

I think the bug is in the [get](https://github.com/drewkerrigan/nagios-http-json/blob/47a37556ba96b322b8a4c95b482034eb80a8ec95/check_http_json.py#L155) function:
```
        if temp_data:
            data = temp_data
        else:
            data = self.data
```

Since the value (in my case Integer 0) is passed to the get function as "temp_data" by getSubArrayElement, that check of temp_data returns "false".
I assumed that codeline is supposed to check if temp_data is empty and changed it to
```
        if temp_data != '':
            data = temp_data
        else:
            data = self.data
```
which seems to have fixed it.

**Comment by martialblog** [comment]
Hi, thanks for the feedback. Can you give me an example if your data? I want to recreate the but in a unittest.

**Comment by martialblog** [comment]
Was fixed in https://github.com/drewkerrigan/nagios-http-json/pull/66

**Comment by vanso-hubsi** [comment]
Thank you for the fix. 👍 
And I'm sorry, seems I missed your request for a data sample. Only saw it now when you closed this issue 😉 .
