### ISSUE TITLE
json starting with square bracket

### ISSUE THREAD

**Issue by vabastiil** [drewkerrigan/nagios-http-json#8]
How to access specific JSON field when json is starting with square bracket?

Example:
[
{ "gauges": { "jvm.buffers.direct.capacity": {"value": 215415}}}
]

**Comment by drewkerrigan** [comment]
Hello @vabastiil, I've just committed a fix that allows this behavior: 

If the root of the JSON data is itself an array like the following:

```
[
{ "gauges": { "jvm.buffers.direct.capacity": {"value": 215415}}}
]
```

The beginning of the key should start with ($index) as in this example:

```
./check_http_json.py -H localhost:8081 -p metrics --key_exists "(0)_gauges_jvm.buffers.direct.capacity_value" -f _
```

**Comment by vabastiil** [comment]
Thank you for quick response!
Working great now!
