### ISSUE TITLE
Please add an optional parameter to mitigate unknown to critical

### ISSUE THREAD

**Issue by K0nne** [drewkerrigan/nagios-http-json#82]
Hello,

we have a few cases where the check cant get results, because of unreachability. In this the check returns unknown. We whould like have an option mitigate this to critical.

**Comment by martialblog** [comment]
Hi, yes it should be possible to provide a flag to override the exit code.

**Comment by martialblog** [comment]
Implemented this feature here: https://github.com/drewkerrigan/nagios-http-json/pull/86

**Comment by K0nne** [comment]
It works perfect.
